name: Laravel

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: "8.1"
      - name: Sutup Node
        uses: actions/setup-node@v2
        with:
          node-version: "18"
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Install Node dependencies
        run: npm ci
      - name: Build assets
        run: npm run build
      - name: Set directory permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Setup SSH key
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          KNOWN_HOSTS: ${{ secrets.SSH_HOST }}
        run: |
          sudo apt-get update
          sudo apt-get install -y libssl-dev openssh-client
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $KNOWN_HOSTS >> ~/.ssh/known_hosts
